---
title:  "Process CA FRP data"
author: "JJWalker"
date: "2021-08-25"
output:
  html_notebook:
    highlight: tango
    mathjax: null
    number_sections: no
    theme: spacelab
---


####_3_process_ca_frp_data.Rmd_

This script inputs the joined FRP/EVT datasets produced in script #2 and outputs R data files for further processing.  

_Input files_:  maxFRP_CA_gte4sqkm_2014to2020_fireInfo_evtClasses.csv  

_Output file_:  processed_data_prior_to_new_df.RData

```{r, echo=FALSE}

# Prior to input, FRP files are processed as follows: 
#  * Formatted from GEE format to ArcMap-ready (_1_format_gee_file_for_import_into_arc.R_)
#  * Intersected with the BLM fire history file (_intersect_frp_data_with_fire_perimeters.py_) to combine 
#    * FRP data
#    * Fire history information  
#  * Joined with EVT information (_2_add_evtclass_to_gee_files.Rmd_)

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

# ---------------------------------------------------------------- #
#### Set up directories and filenames ####
# ---------------------------------------------------------------- #
load_libraries <- function(libs){
  for(lib in libs){
    if(!require(lib, character.only = TRUE)){    # Require returns TRUE if package loaded
      install.packages(lib, dependencies = TRUE) # If package couldn't load, re-install
      require(lib, character.only = TRUE)        # Load package after installing
    }
  }
}
#  Try/install packages
load_libraries(c("lubridate", "dplyr") )

# Set paths
path_in = "/home/jovyan/ca_frp"
path_data <- file.path(path_in, "data")
path_r <- file.path(path_in, "R")
data_in <- "maxFRP_CA_gte4sqkm_2014to2020_fireInfo_evtClasses.csv"
rdata <- "processed_data_prior_to_new_df.RData"

```


```{r, echo = F}

# ---------------------------------------------------------------- #
#### Combine annual files ####
# ---------------------------------------------------------------- #

# Get the relevant filename
  files_all <- read.csv(file.path(path_data, data_in), header = T)

```


```{r, echo = F}

# ---------------------------------------------------------------- #
#### Select columns ####
# ---------------------------------------------------------------- #
  x_orig <- files_all %>% 
                select(index,  MaxFRP.x, latitude.x, longitude.x, ALARM_DATE,
                       sample, satellite, newdate.y, YEAR_, FID_firep2, FIRE_NAME, GIS_ACRES, pixelarea, starts_with('class')) 
 
```


```{r, echo = F}

# ---------------------------------------------------------------- #
#### Define EVT columns ####
# ---------------------------------------------------------------- #
# Read in data file from GDrive:  "MyDrive/Work/projects/ca_frp/evt_classes_found_in_ca.csv"

data_url <- "1y3DCmYOZFBf0G2_VfdnMHFHAyo2pfGpW" # google file ID
evt_classes <- read.csv(sprintf("https://docs.google.com/uc?id=%s&export=download", data_url))


# Change column names to conform to existing 
names(evt_classes) <- c('evt_number', 'description', 'evt_group')
 
```


```{r, echo = FALSE}

# ---------------------------------------------------------------- #
#### File clean up and formatting ####
# ---------------------------------------------------------------- #

# Point ID ('index') is unique to each point, though the same ID can occur in multiple rows since
# a single point may have burned in multiple fires. The input format is unwieldy; replace with 
# a simpler sequence of sequential numbers.

  x_orig <- x_orig %>% 
            mutate(index = as.factor(index))

  levels(x_orig$index) <- c(seq(1:length(levels(x_orig$index))))
  
# Rename columns  
  oldnames = c("index","MaxFRP.x", "newdate.y", "ALARM_DATE", "YEAR_", "FID_firep2", "FIRE_NAME", "GIS_ACRES", "latitude.x", "longitude.x")
  newnames = c("ptid", "frp", "modis_date", "fire_date", "fire_year", "fireid", "fire_name", "fire_ac", "lat", "lon")
  x_orig <- x_orig %>% rename_at(vars(oldnames), ~ newnames)

# Incoming MODIS frp is scaled by 10; rescale
  x_orig$frp <- 0.1 * x_orig$frp
  
# Remove NA-only columns
  x_orig <- Filter(function(y) !all(is.na(y)), x_orig)

  # Remove rows in which frp == NA
  x_orig <- x_orig[!is.na(x_orig$frp), ]
  
# Remove rows in which all classes == NA
 # col_start <- which(colnames(x_orig) == "class11")
 # col_end <- which(colnames(x_orig) == "class82")
 # x_orig <- x_orig[!apply(x_orig[col_start:col_end], 1, function(x) all(is.na(x))), ]
  
# Format date columns and remove old ones
  x_orig$modis_date <- as.Date(x_orig$modis_date, format = "%Y-%m-%d")  #"%Y-%m-%d")
  x_orig$fire_date <- as.Date(x_orig$fire_date, format = "%m/%d/%Y %H:%M:%S")
  x_orig$modis_year <- year(x_orig$modis_date)
  
# Ensure point id is a factor
  x_orig$ptid <- factor(x_orig$ptid)
  
# Remove unneeded columns
# x_orig <- x_orig %>% select(-c(DiscDate, newdate))
  
# Remove all rows in which the modis date preceeds the fire date
   x_orig <- x_orig[which(x_orig$modis_date > x_orig$fire_date), ]

```
###Assemble new dataframe of fires


```{r, echo=FALSE, warning=F}

# ---------------------------------------------------------------- #
#### Set up the new fire df ####
# ---------------------------------------------------------------- #

# We need a row for each unique fire_year and modis_year.
# fire_years are derived from the CA fire history database; modis_years are from FRP data.
# Both are necessary since some modis_years do not have a corresponding fire_year.
# Each will have an FRP value for each MODIS year; pre-MODIS years get frp = NA.

# Set up df to hold entries for all points
  x_holder <- setNames(data.frame(matrix(ncol = 8, nrow = 0)),  c('ptid', 'lat', 'long', 'fire_year', 'frp', 'fireid', 'sample',  'satellite'))

# Create df without classes
  x_noclasses <- x_orig %>% select(-starts_with('class'))
  
# Create df of classes info for each pixel. Remove duplicates to get 1 row for each ptid. Include areal sum for each pixel
  x_classes <- x_orig %>% 
                select(ptid, starts_with('class')) %>% 
                distinct(ptid, .keep_all = T) %>% 
                mutate(evt_sum = rowSums(.[,-1], na.rm = TRUE))

```


####Save data

RData file is saved to `r file.path(path_r, rdata)`

```{r, echo=FALSE}

# Save data and environment settings   
print(paste0("R data file saved to ", file.path(path_r, rdata)))
#save.image(file = file.path(path_r, rdata))
save(x_holder, x_noclasses, x_classes, file = file.path(path_r, rdata) )

```